Added backup/restore scripts

diff --git a/scripts/destroy b/scripts/destroy
--- a/scripts/destroy
+++ b/scripts/destroy
@@ -3,6 +3,13 @@
 BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
 cd "$BASE_DIR"
 
+backup=tmp/backup.tar.gz
+if ! [ -f $backup ]
+then
+  echo "File $PWD/$backup not found. Aborting!"
+  exit 1
+fi
+
 read -p "Are you sure (type Y or y to proceed)? " -n 1 -r
 if [[ $REPLY =~ ^[Yy]$ ]]
 then
